# Generated by Django 5.0.6 on 2024-06-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('summary', models.TextField()),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.CharField(blank=True, max_length=255, null=True)),
                ('view_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_score', models.FloatField(blank=True, null=True)),
                ('awards_received', models.FloatField(blank=True, null=True)),
                ('awards_nominated_for', models.FloatField(blank=True, null=True)),
                ('boxoffice', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('netflix_release_date', models.DateField(blank=True, null=True)),
                ('production_house', models.CharField(blank=True, max_length=255, null=True)),
                ('netflix_link', models.URLField(blank=True, null=True)),
                ('imdb_votes', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
